<?php

use Illuminate\Database\Seeder;

class GlobalWording extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $globalwording=[
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"5",
                "wording"=>"Hati-hati dia musuh! Jagain cewe lo baik-baik!",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"6",
                "wording"=>"Waahhh dia suka sama cewek lu jangan di temenin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"7",
                "wording"=>"Dia jorok gak mandi mulu ngapain di temenin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"8",
                "wording"=>"Bucin bgt orangnya awas nanti kau ketularan",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"9",
                "wording"=>"Dia suka curi pandang cewek lu hati-hati ya bro",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"10",
                "wording"=>"Wah orangnya minta rokok sebatang terus jauhin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"11",
                "wording"=>"Ngembat rokok aja berani bisa bisa cewek lu diambil juga bro :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"12",
                "wording"=>"Bau ketek orangnya ihhhh jauhin deh hehhehe",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"13",
                "wording"=>"Doi nebeng motor lu mulu jangan mau deh temenan lagi",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"14",
                "wording"=>"Hati-hati kalau lagi susah dia ngejauh kalau lagi seneng so baik",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"15",
                "wording"=>"Harus waspada sama yang beginian ni",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"16",
                "wording"=>"Waahhh dia suka sama cewek lu jangan di temenin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"17",
                "wording"=>"Dia jorok gak mandi mulu ngapain di temenin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"18",
                "wording"=>"Bucin bgt orangnya awas nanti kau ketularan",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"19",
                "wording"=>"Dia suka curi pandang cewek lu hati-hati ya bro",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"20",
                "wording"=>"Wah orangnya minta rokok sebatang terus jauhin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"21",
                "wording"=>"Ngembat rokok aja berani bisa bisa cewek lu diambil juga bro :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"22",
                "wording"=>"Bau ketek orangnya ihhhh jauhin deh hehhehe",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"23",
                "wording"=>"Doi nebeng motor lu mulu jangan mau deh temenan lagi",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"24",
                "wording"=>"Hati-hati kalau lagi susah dia ngejauh kalau lagi seneng so baik",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"25",
                "wording"=>"Harus waspada sama yang beginian ni",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"26",
                "wording"=>"Waahhh dia suka sama cewek lu jangan di temenin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"27",
                "wording"=>"Dia jorok gak mandi mulu ngapain di temenin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"28",
                "wording"=>"Bucin bgt orangnya awas nanti kau ketularan",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"29",
                "wording"=>"Dia suka curi pandang cewek lu hati-hati ya bro",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"30",
                "wording"=>"Wah orangnya minta rokok sebatang terus jauhin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"31",
                "wording"=>"Ngembat rokok aja berani bisa bisa cewek lu diambil juga bro :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"32",
                "wording"=>"Bau ketek orangnya ihhhh jauhin deh hehhehe",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"33",
                "wording"=>"Doi nebeng motor lu mulu jangan mau deh temenan lagi",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"34",
                "wording"=>"Hati-hati kalau lagi susah dia ngejauh kalau lagi seneng so baik",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"35",
                "wording"=>"Harus waspada sama yang beginian ni",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"36",
                "wording"=>"Waahhh dia suka sama cewek lu jangan di temenin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"37",
                "wording"=>"Dia jorok gak mandi mulu ngapain di temenin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"38",
                "wording"=>"Bucin bgt orangnya awas nanti kau ketularan",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"39",
                "wording"=>"Dia suka curi pandang cewek lu hati-hati ya bro",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"40",
                "wording"=>"Wah orangnya minta rokok sebatang terus jauhin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"41",
                "wording"=>"Ngembat rokok aja berani bisa bisa cewek lu diambil juga bro :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"42",
                "wording"=>"Bau ketek orangnya ihhhh jauhin deh hehhehe",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"43",
                "wording"=>"Doi nebeng motor lu mulu jangan mau deh temenan lagi",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"44",
                "wording"=>"Hati-hati kalau lagi susah dia ngejauh kalau lagi seneng so baik",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"45",
                "wording"=>"Harus waspada sama yang beginian ni",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"46",
                "wording"=>"Waahhh dia suka sama cewek lu jangan di temenin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"47",
                "wording"=>"Dia jorok gak mandi mulu ngapain di temenin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"48",
                "wording"=>"Bucin bgt orangnya awas nanti kau ketularan",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"49",
                "wording"=>"Dia suka curi pandang cewek lu hati-hati ya bro",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"50",
                "wording"=>"Wah orangnya minta rokok sebatang terus jauhin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"51",
                "wording"=>"Ngembat rokok aja berani bisa bisa cewek lu diambil juga bro :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"52",
                "wording"=>"Bau ketek orangnya ihhhh jauhin deh hehhehe",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"53",
                "wording"=>"Doi nebeng motor lu mulu jangan mau deh temenan lagi",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"54",
                "wording"=>"Hati-hati kalau lagi susah dia ngejauh kalau lagi seneng so baik",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"55",
                "wording"=>"Harus waspada sama yang beginian ni",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"56",
                "wording"=>"Waahhh dia suka sama cewek lu jangan di temenin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"57",
                "wording"=>"Dia jorok gak mandi mulu ngapain di temenin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"58",
                "wording"=>"Bucin bgt orangnya awas nanti kau ketularan",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"59",
                "wording"=>"Dia suka curi pandang cewek lu hati-hati ya bro",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"60",
                "wording"=>"Wah orangnya minta rokok sebatang terus jauhin deh",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"61",
                "wording"=>"Ngembat rokok aja berani bisa bisa cewek lu diambil juga bro :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"62",
                "wording"=>"Bau ketek orangnya ihhhh jauhin deh hehhehe",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"63",
                "wording"=>"Doi nebeng motor lu mulu jangan mau deh temenan lagi",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"64",
                "wording"=>"Hati-hati kalau lagi susah dia ngejauh kalau lagi seneng so baik",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"65",
                "wording"=>"Cocok sekali kalian berdua Jadi Sahabat",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"66",
                "wording"=>"Hatinya tulus untuk jadi sahabat lu bro !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"67",
                "wording"=>"Sehati banget sih kalian berdua ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"68",
                "wording"=>"Lo berdua bro banget! Silahkan tukeran celana dalem ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"69",
                "wording"=>"Kalian cocok sekali sahabatan sampai mati ya :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"70",
                "wording"=>"SELAMAT kalian BFF sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"71",
                "wording"=>"SELAMAT kalian Bisa jadi sahabat sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"72",
                "wording"=>"Cocok sekali kalian berdua Jadi Sahabat",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"73",
                "wording"=>"Hatinya tulus untuk jadi sahabat lu bro !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"74",
                "wording"=>"Sehati banget sih kalian berdua ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"75",
                "wording"=>"Lo berdua bro banget! Silahkan tukeran celana dalem ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"76",
                "wording"=>"Kalian cocok sekali sahabatan sampai mati ya :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"77",
                "wording"=>"SELAMAT kalian BFF sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"78",
                "wording"=>"SELAMAT kalian Bisa jadi sahabat sampai mati !",
            ],[
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"79",
                "wording"=>"Kalian cocok sekali sahabatan sampai mati ya :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"80",
                "wording"=>"SELAMAT kalian BFF sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"81",
                "wording"=>"SELAMAT kalian Bisa jadi sahabat sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"82",
                "wording"=>"Cocok sekali kalian berdua Jadi Sahabat",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"83",
                "wording"=>"Hatinya tulus untuk jadi sahabat lu bro !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"84",
                "wording"=>"Sehati banget sih kalian berdua ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"85",
                "wording"=>"Lo berdua bro banget! Silahkan tukeran celana dalem ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"86",
                "wording"=>"Kalian cocok sekali sahabatan sampai mati ya :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"87",
                "wording"=>"SELAMAT kalian BFF sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"88",
                "wording"=>"SELAMAT kalian Bisa jadi sahabat sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"89",
                "wording"=>"Kalian cocok sekali sahabatan sampai mati ya :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"90",
                "wording"=>"SELAMAT kalian BFF sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"91",
                "wording"=>"SELAMAT kalian Bisa jadi sahabat sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"92",
                "wording"=>"Cocok sekali kalian berdua Jadi Sahabat",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"93",
                "wording"=>"Hatinya tulus untuk jadi sahabat lu bro !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"94",
                "wording"=>"Sehati banget sih kalian berdua ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"95",
                "wording"=>"Lo berdua bro banget! Silahkan tukeran celana dalem ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"96",
                "wording"=>"Kalian cocok sekali sahabatan sampai mati ya :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"97",
                "wording"=>"SELAMAT kalian BFF sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"98",
                "wording"=>"SELAMAT kalian Bisa jadi sahabat sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"99",
                "wording"=>"SELAMAT kalian BFF sampai mati !",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"1",
                "value"=>"100",
                "wording"=>"SELAMAT kalian Bisa jadi sahabat sampai mati !",
            ],

            //=======Cewek Cewek======
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"5",
                "wording"=>"Katanya BFF tapi kok nusuk dari belakang :( Hati-hati",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"6",
                "wording"=>"Dia jahat sama kamu jauhin deh !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"7",
                "wording"=>"Jangan main sama dia tuh biang gosip",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"8",
                "wording"=>"Jangan mau temenan dia pelit orangnya",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"9",
                "wording"=>"Dia suka sama cowok girls hati-hati !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"10",
                "wording"=>"Lipstik aja gk modal gimana mau di ajak pergi main",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"11",
                "wording"=>"Utangnya banyak mending jauhin deh hahahha",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"12",
                "wording"=>"BBF sih tapi ngomongin di belakang",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"13",
                "wording"=>"Main sama dia tapi lu mulu yang bayarin makannya :(",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"14",
                "wording"=>"Pelit doi ngapain main sama dia",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"15",
                "wording"=>"Harus waspada sama yang beginian ni",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"16",
                "wording"=>"Dia jahat sama kamu jauhin deh !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"17",
                "wording"=>"Jangan main sama dia tuh biang gosip",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"18",
                "wording"=>"Jangan mau temenan dia pelit orangnya",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"19",
                "wording"=>"Dia suka sama cowok girls hati-hati !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"20",
                "wording"=>"Lipstik aja gk modal gimana mau di ajak pergi main",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"21",
                "wording"=>"Utangnya banyak mending jauhin deh hahahha",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"22",
                "wording"=>"BBF sih tapi ngomongin di belakang",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"23",
                "wording"=>"Main sama dia tapi lu mulu yang bayarin makannya :(",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"24",
                "wording"=>"Pelit doi ngapain main sama dia",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"25",
                "wording"=>"Harus waspada sama yang beginian ni",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"26",
                "wording"=>"Dia jahat sama kamu jauhin deh !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"27",
                "wording"=>"Jangan main sama dia tuh biang gosip",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"28",
                "wording"=>"Jangan mau temenan dia pelit orangnya",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"29",
                "wording"=>"Dia suka sama cowok girls hati-hati !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"30",
                "wording"=>"Lipstik aja gk modal gimana mau di ajak pergi main",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"31",
                "wording"=>"Utangnya banyak mending jauhin deh hahahha",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"32",
                "wording"=>"BBF sih tapi ngomongin di belakang",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"33",
                "wording"=>"Main sama dia tapi lu mulu yang bayarin makannya :(",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"34",
                "wording"=>"Pelit doi ngapain main sama dia",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"35",
                "wording"=>"Harus waspada sama yang beginian ni",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"36",
                "wording"=>"Dia jahat sama kamu jauhin deh !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"37",
                "wording"=>"Jangan main sama dia tuh biang gosip",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"38",
                "wording"=>"Jangan mau temenan dia pelit orangnya",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"39",
                "wording"=>"Dia suka sama cowok girls hati-hati !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"40",
                "wording"=>"Lipstik aja gk modal gimana mau di ajak pergi main",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"41",
                "wording"=>"Utangnya banyak mending jauhin deh hahahha",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"42",
                "wording"=>"BBF sih tapi ngomongin di belakang",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"43",
                "wording"=>"Main sama dia tapi lu mulu yang bayarin makannya :(",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"44",
                "wording"=>"Pelit doi ngapain main sama dia",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"45",
                "wording"=>"Harus waspada sama yang beginian ni",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"46",
                "wording"=>"Dia jahat sama kamu jauhin deh !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"47",
                "wording"=>"Jangan main sama dia tuh biang gosip",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"48",
                "wording"=>"Jangan mau temenan dia pelit orangnya",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"49",
                "wording"=>"Dia suka sama cowok girls hati-hati !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"50",
                "wording"=>"Lipstik aja gk modal gimana mau di ajak pergi main",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"51",
                "wording"=>"Utangnya banyak mending jauhin deh hahahha",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"52",
                "wording"=>"BBF sih tapi ngomongin di belakang",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"53",
                "wording"=>"Main sama dia tapi lu mulu yang bayarin makannya :(",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"54",
                "wording"=>"Pelit doi ngapain main sama dia",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"55",
                "wording"=>"Harus waspada sama yang beginian ni",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"56",
                "wording"=>"Dia jahat sama kamu jauhin deh !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"57",
                "wording"=>"Jangan main sama dia tuh biang gosip",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"58",
                "wording"=>"Jangan mau temenan dia pelit orangnya",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"59",
                "wording"=>"Dia suka sama cowok girls hati-hati !!",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"60",
                "wording"=>"Lipstik aja gk modal gimana mau di ajak pergi main",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"61",
                "wording"=>"Hobi kalian sama selamat bisa jadi BFF",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"62",
                "wording"=>"Kalian bisa jadi sahabat dan saudara ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"63",
                "wording"=>"Best Friend Forever sampai akhir nanti",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"64",
                "wording"=>"Sahabat sejati! ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"65",
                "wording"=>"Cocok Banget jadi sahabat sejati",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"66",
                "wording"=>"Sahabat sejati sampai mati !",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"67",
                "wording"=>"Hobi kalian sama selamat bisa jadi BFF",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"68",
                "wording"=>"Kalian bisa jadi sahabat dan saudara ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"69",
                "wording"=>"Best Friend Forever sampai akhir nanti",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"70",
                "wording"=>"Cocok Banget jadi sahabat sejati",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"71",
                "wording"=>"Hobi kalian sama selamat bisa jadi BFF",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"72",
                "wording"=>"Kalian bisa jadi sahabat dan saudara ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"73",
                "wording"=>"Best Friend Forever sampai akhir nanti",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"74",
                "wording"=>"Sahabat sejati! ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"75",
                "wording"=>"Cocok Banget jadi sahabat sejati",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"76",
                "wording"=>"Sahabat sejati sampai mati !",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"77",
                "wording"=>"Hobi kalian sama selamat bisa jadi BFF",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"78",
                "wording"=>"Kalian bisa jadi sahabat dan saudara ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"79",
                "wording"=>"Best Friend Forever sampai akhir nanti",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"80",
                "wording"=>"Cocok Banget jadi sahabat sejati",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"81",
                "wording"=>"Hobi kalian sama selamat bisa jadi BFF",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"82",
                "wording"=>"Kalian bisa jadi sahabat dan saudara ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"83",
                "wording"=>"Best Friend Forever sampai akhir nanti",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"84",
                "wording"=>"Sahabat sejati! ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"85",
                "wording"=>"Cocok Banget jadi sahabat sejati",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"86",
                "wording"=>"Sahabat sejati sampai mati !",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"87",
                "wording"=>"Hobi kalian sama selamat bisa jadi BFF",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"88",
                "wording"=>"Kalian bisa jadi sahabat dan saudara ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"89",
                "wording"=>"Best Friend Forever sampai akhir nanti",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"90",
                "wording"=>"Cocok Banget jadi sahabat sejati",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"91",
                "wording"=>"Hobi kalian sama selamat bisa jadi BFF",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"92",
                "wording"=>"Kalian bisa jadi sahabat dan saudara ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"93",
                "wording"=>"Best Friend Forever sampai akhir nanti",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"94",
                "wording"=>"Sahabat sejati! ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"95",
                "wording"=>"Cocok Banget jadi sahabat sejati",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"96",
                "wording"=>"Sahabat sejati sampai mati !",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"97",
                "wording"=>"Hobi kalian sama selamat bisa jadi BFF",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"98",
                "wording"=>"Kalian bisa jadi sahabat dan saudara ",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"99",
                "wording"=>"Best Friend Forever sampai akhir nanti",
            ],
            [
                "gender_of_key1"=>"0",
                "gender_of_key2" =>"0",
                "value"=>"100",
                "wording"=>"Cocok Banget jadi sahabat sejati",
            ],

            // ========== Cewek Cowok =================
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"5",
                "wording"=>"Katanya BFF tapi kok nusuk dari belakang :( Hati-hati",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"6",
                "wording"=>"Kayanya dia bukan jodohmu :( tapi kalo kamu maksa yaudah :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"7",
                "wording"=>"Siap-siap di PHP-in yaaaaa :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"8",
                "wording"=>"Abis suka terus ditinggal, emang enak? Hati-hati sama dia",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"9",
                "wording"=>"Kamu suka dia, tapi dia suka yang lain :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"10",
                "wording"=>"Yaahhh kamu jelek dia gak mayu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"11",
                "wording"=>"Muka kamu jelek sih jadi dijauhin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"12",
                "wording"=>"Mau enaknya doang abis itu di tinggal :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"13",
                "wording"=>"Main sama dia tapi lu mulu yang bayarin makannya :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"14",
                "wording"=>"Doi punya niat jahat sama kamu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"15",
                "wording"=>"Pacarnya segudang yakin mau sama doi :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"16",
                "wording"=>"Kayanya dia bukan jodohmu :( tapi kalo kamu maksa yaudah :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"17",
                "wording"=>"Siap-siap di PHP-in yaaaaa :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"18",
                "wording"=>"Abis suka terus ditinggal, emang enak? Hati-hati sama dia",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"19",
                "wording"=>"Kamu suka dia, tapi dia suka yang lain :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"20",
                "wording"=>"Yaahhh kamu jelek dia gak mayu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"21",
                "wording"=>"Muka kamu jelek sih jadi dijauhin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"22",
                "wording"=>"Mau enaknya doang abis itu di tinggal :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"23",
                "wording"=>"Main sama dia tapi lu mulu yang bayarin makannya :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"24",
                "wording"=>"Doi punya niat jahat sama kamu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"25",
                "wording"=>"Pacarnya segudang yakin mau sama doi :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"26",
                "wording"=>"Kayanya dia bukan jodohmu :( tapi kalo kamu maksa yaudah :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"27",
                "wording"=>"Siap-siap di PHP-in yaaaaa :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"28",
                "wording"=>"Abis suka terus ditinggal, emang enak? Hati-hati sama dia",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"29",
                "wording"=>"Kamu suka dia, tapi dia suka yang lain :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"30",
                "wording"=>"Yaahhh kamu jelek dia gak mayu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"31",
                "wording"=>"Muka kamu jelek sih jadi dijauhin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"32",
                "wording"=>"Mau enaknya doang abis itu di tinggal :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"33",
                "wording"=>"Main sama dia tapi lu mulu yang bayarin makannya :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"34",
                "wording"=>"Doi punya niat jahat sama kamu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"35",
                "wording"=>"Pacarnya segudang yakin mau sama doi :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"36",
                "wording"=>"Kayanya dia bukan jodohmu :( tapi kalo kamu maksa yaudah :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"37",
                "wording"=>"Siap-siap di PHP-in yaaaaa :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"38",
                "wording"=>"Abis suka terus ditinggal, emang enak? Hati-hati sama dia",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"39",
                "wording"=>"Kamu suka dia, tapi dia suka yang lain :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"40",
                "wording"=>"Yaahhh kamu jelek dia gak mayu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"41",
                "wording"=>"Muka kamu jelek sih jadi dijauhin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"42",
                "wording"=>"Mau enaknya doang abis itu di tinggal :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"43",
                "wording"=>"Main sama dia tapi lu mulu yang bayarin makannya :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"44",
                "wording"=>"Doi punya niat jahat sama kamu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"45",
                "wording"=>"Pacarnya segudang yakin mau sama doi :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"46",
                "wording"=>"Kayanya dia bukan jodohmu :( tapi kalo kamu maksa yaudah :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"47",
                "wording"=>"Siap-siap di PHP-in yaaaaa :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"48",
                "wording"=>"Abis suka terus ditinggal, emang enak? Hati-hati sama dia",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"49",
                "wording"=>"Kamu suka dia, tapi dia suka yang lain :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"50",
                "wording"=>"Yaahhh kamu jelek dia gak mayu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"51",
                "wording"=>"Muka kamu jelek sih jadi dijauhin",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"52",
                "wording"=>"Mau enaknya doang abis itu di tinggal :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"53",
                "wording"=>"Main sama dia tapi lu mulu yang bayarin makannya :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"54",
                "wording"=>"Doi punya niat jahat sama kamu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"55",
                "wording"=>"Pacarnya segudang yakin mau sama doi :)",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"56",
                "wording"=>"Kayanya dia bukan jodohmu :( tapi kalo kamu maksa yaudah :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"57",
                "wording"=>"Siap-siap di PHP-in yaaaaa :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"58",
                "wording"=>"Abis suka terus ditinggal, emang enak? Hati-hati sama dia",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"59",
                "wording"=>"Kamu suka dia, tapi dia suka yang lain :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"60",
                "wording"=>"Yaahhh kamu jelek dia gak mayu :(",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"61",
                "wording"=>"Kalian cocok seperti pangeran dan tuan putri",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"62",
                "wording"=>"Kalian pasangan yang serasi! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"63",
                "wording"=>"Kalian pasangan yang cocok sekali !!",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"64",
                "wording"=>"Sahabat sejati! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"65",
                "wording"=>"SELAMAT KALIAN BERJODOH",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"66",
                "wording"=>"Sepertinya dia jodohmu ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"67",
                "wording"=>"Kalian cocok seperti pangeran dan tuan putri",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"68",
                "wording"=>"Kalian pasangan yang serasi! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"69",
                "wording"=>"Kalian pasangan yang cocok sekali !!",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"70",
                "wording"=>"SELAMAT KALIAN BERJODOH",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"71",
                "wording"=>"Kalian cocok seperti pangeran dan tuan putri",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"72",
                "wording"=>"Kalian pasangan yang serasi! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"73",
                "wording"=>"Kalian pasangan yang cocok sekali !!",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"74",
                "wording"=>"Sahabat sejati! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"75",
                "wording"=>"SELAMAT KALIAN BERJODOH",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"76",
                "wording"=>"Sepertinya dia jodohmu ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"77",
                "wording"=>"Kalian cocok seperti pangeran dan tuan putri",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"78",
                "wording"=>"Kalian pasangan yang serasi! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"79",
                "wording"=>"Kalian pasangan yang cocok sekali !!",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"80",
                "wording"=>"SELAMAT KALIAN BERJODOH",
            ], [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"81",
                "wording"=>"Kalian cocok seperti pangeran dan tuan putri",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"82",
                "wording"=>"Kalian pasangan yang serasi! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"83",
                "wording"=>"Kalian pasangan yang cocok sekali !!",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"84",
                "wording"=>"Sahabat sejati! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"85",
                "wording"=>"SELAMAT KALIAN BERJODOH",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"86",
                "wording"=>"Sepertinya dia jodohmu ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"87",
                "wording"=>"Kalian cocok seperti pangeran dan tuan putri",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"88",
                "wording"=>"Kalian pasangan yang serasi! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"89",
                "wording"=>"Kalian pasangan yang cocok sekali !!",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"90",
                "wording"=>"SELAMAT KALIAN BERJODOH",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"91",
                "wording"=>"Kalian cocok seperti pangeran dan tuan putri",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"92",
                "wording"=>"Kalian pasangan yang serasi! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"93",
                "wording"=>"Kalian pasangan yang cocok sekali !!",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"94",
                "wording"=>"Sahabat sejati! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"95",
                "wording"=>"SELAMAT KALIAN BERJODOH",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"96",
                "wording"=>"Sepertinya dia jodohmu ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"97",
                "wording"=>"Kalian cocok seperti pangeran dan tuan putri",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"98",
                "wording"=>"Kalian pasangan yang serasi! ",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"99",
                "wording"=>"Kalian pasangan yang cocok sekali !!",
            ],
            [
                "gender_of_key1"=>"1",
                "gender_of_key2" =>"0",
                "value"=>"100",
                "wording"=>"SELAMAT KALIAN BERJODOH",
            ]

           

        ];

        foreach ($globalwording as $value) {
            DB::table('global_wordings')->insert($value);
        }
    }
}
